CREATE TABLE IF NOT EXISTS role
(
    id       BIGSERIAL PRIMARY KEY NOT NULL,
    name     TEXT UNIQUE
    );

CREATE TABLE IF NOT EXISTS person
(
    id       BIGSERIAL PRIMARY KEY NOT NULL,
    login    TEXT UNIQUE,
    password TEXT,
    role_id BIGINT
    );

ALTER TABLE person ADD CONSTRAINT fk_person_role FOREIGN KEY (role_id) REFERENCES role(id)
    ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS room
(
    id      BIGSERIAL PRIMARY KEY NOT NULL,
    name    TEXT,
    admin_id BIGINT
    );

ALTER TABLE room ADD CONSTRAINT fk_room_person FOREIGN KEY (admin_id) REFERENCES person(id)
    ON DELETE CASCADE ON UPDATE CASCADE;


CREATE TABLE IF NOT EXISTS message
(
    id        BIGSERIAL PRIMARY KEY NOT NULL,
    text      TEXT,
    room_id   BIGINT NOT NULL,
    person_id BIGINT NOT NULL
);

ALTER TABLE message ADD CONSTRAINT fk_message_room FOREIGN KEY (room_id) REFERENCES room(id)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE message ADD CONSTRAINT fk_message_person FOREIGN KEY (person_id)  REFERENCES person(id)
    ON DELETE CASCADE ON UPDATE CASCADE;
